#!/bin/bash

echo "Start installing some stuff.."

monkey_progs=(
	firefox 
	htop 
	adb
       	git
	zsh
	chromium-browser
	vim
	python
	tree
)

sudo apt update && sudo apt upgrade && sudo apt install $monkey_progs

unset monkey_progs

echo "I finished installing"
